var urlInfo=require('./config').visit_url;
module.exports={
    'button':[
            {
            'name':'游戏介绍',
            'sub_button':[
                {
                    'type':'view',
                    'name':'IOS下载',
                    'url':'http://a.app.qq.com/o/simple.jsp?pkgname=com.haishiydmm.fish'
                },
                {
                    'type':'view',
                    'name':'安卓下载',
                    'url':'http://a.app.qq.com/o/simple.jsp?pkgname=com.haishiydmm.fish'
                },
                {
                    'type':'view',
                    'name':'游戏介绍',
                    'url':'http://www.wmcyou.com/cpzx'
                },
                {
                    'type':'view',
                    'name':'账号绑定或解绑',
                    'url':urlInfo.code
                },
                {
                    'type':'view',
                    'name':'官网',
                    'url':'https://www.wanchuangyou.com/'
                }
            ]
        },
        {
            'name':'福利社',
            'sub_button':[
                {
                    'type':'view',
                    'name':'签到奖励',
                    'url':urlInfo.page
                },
                {
                    'name':'充值优惠',
                    'type':'view',
                    'url':urlInfo.mall
                },
                {
                    'name':'活动',
                    'type':'view',
                    'url':urlInfo.active
                },
                {
                    'name':'小游戏赢大奖',
                    'type':'view',
                    'url':urlInfo.miniGame
                }
            ]
        },
        {
            'name':'客服中心',
            'sub_button':[
                {
                    'name':'QQ',
                    'type':'view',
                    'url':'http://sighttp.qq.com/authd?IDKEY=67ea2db16ee25ff42617b36476a9f71de432211d810e860a'
                },
                {
                    'name':'玩家交流群',
                    'type':'view',
                    'url':'https://jq.qq.com/?_wv=1027&k=5uw1hQg'
                    
                },
                {
                    'name':'截图上传',
                    'type':'view',
                    'url':urlInfo.upload
                }
            ]
        }
    ]
}
